controllers:
  resource: ../src/Controller/
  type: attribute

# config/routes.yaml

# the "app_lucky_number" route name is not important yet
app_lucky_number:
  path: /lucky/number
  controller: App\Controller\LuckyController::number
# app_accueil:
#   path: /utilisateur
#   controller: App\Controller\UtilisateurController
